### ISSUE TITLE
Needs a README.md .

### ISSUE THREAD

**Issue by Asutosh989** [Asutosh989/twitter-splitter#2]

**Comment by DigitalDesignerOnline** [comment]
may I be of assistance for this task :)

**Comment by ananyasethi56** [comment]
i want o take this issue

**Comment by Asutosh989** [comment]
@ananyasethi56 you can take this issue. If you need any details do say.

**Comment by Asutosh989** [comment]
@DigitalDesignerOnline I will be creating another issue for beautifying the UI. Can you help me in this?

**Comment by Asutosh989** [comment]
This app splits the long tweets and posts them accordingly to the twitter account. Also, we can search for tweets based on a given keyword. 
@ananyasethi56 I need more details as how to run this app in local environment in the README file.

**Comment by DigitalDesignerOnline** [comment]
for sure :)

**Comment by Harkindey** [comment]
@Asutosh989 Done check PR

**Comment by Asutosh989** [comment]
@Harkindey I have merged the PR. Do check the comment section.

**Comment by Harkindey** [comment]
@Asutosh989 i have made a second PR to fill in for your Comments

**Comment by Priyansh2** [comment]
@Asutosh989  is this issue still open ?

**Comment by Asutosh989** [comment]
@Priyansh2 if you want to suggest some changes in the README.md file, then you can.

**Comment by email2vimalraj** [comment]
@Asutosh989 : Just a question. Does this project require Mongo DB?

**Comment by Asutosh989** [comment]
Actually, it doesn't needs one. But one who had added the twitter auth, had added the MongoDB thing to store user information which is not much needed.

**Comment by email2vimalraj** [comment]
Thanks for confirming.

**Comment by Asutosh989** [comment]
Do you want to make any changes? If so, do inform before creating a PR.

**Comment by email2vimalraj** [comment]
Yes I'm cleaning up certain things and also after Twitter authentication, it is not
redirecting to index file which I'm looking into.

**Comment by raguarack** [comment]
Sorry read as authentication

**Comment by email2vimalraj** [comment]
Sorry read as authentication.

On 19-Oct-2017 3:09 PM, "Vimal Raj" <email2vimalraj@gmail.com> wrote:

Yes I'm cleaning up certain things and also after Twitter author, it is not
redirecting to index file which I'm looking into.

**Comment by Asutosh989** [comment]
@email2vimalraj Thanks for your efforts. I have merged your PR.
